#############################################################################
# Makefile for building: SimpleQtCryptor
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  SimpleQtCryptor.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile SimpleQtCryptor.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I.
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SimpleQtCryptor1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		simpleqtcryptor.cpp \
		simpleqtcryptor_test.cpp 
OBJECTS       = main.o \
		simpleqtcryptor.o \
		simpleqtcryptor_test.o
DIST          = simpleqtcryptor.h \
		simpleqtcryptor_test.h main.cpp \
		simpleqtcryptor.cpp \
		simpleqtcryptor_test.cpp
DESTDIR       = 
TARGET        = SimpleCryptor


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents simpleqtcryptor.h simpleqtcryptor_test.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp simpleqtcryptor.cpp simpleqtcryptor_test.cpp $(DISTDIR)/


clean: 	FORCE
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first


####### Compile

main.o: main.cpp simpleqtcryptor.h \
		simpleqtcryptor_test.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

simpleqtcryptor.o: simpleqtcryptor.cpp simpleqtcryptor.h \
		serpent_sbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simpleqtcryptor.o simpleqtcryptor.cpp

simpleqtcryptor_test.o: simpleqtcryptor_test.cpp simpleqtcryptor_test.h \
		simpleqtcryptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simpleqtcryptor_test.o simpleqtcryptor_test.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

